### ISSUE TITLE
Saga: StoreInBlobStorage does not work

### ISSUE THREAD

**Issue by runes83** [rebus-org/Rebus.AzureStorage#4]
Is there a reason why sagastorage support was removed?

**Comment by mookid8000** [comment]
yes 😐 

It was removed because it is impossible to update blob-based saga data and a corresponding table storage-based index atomically.

This fact introduces a risk that messages get correlated with saga data with which they should not have been correlated.

I do not have the nerves to distribute code that can fail like that.

If anyone feels strongly about getting it back, I suggest you create a separate NuGet package, possibly grabbing the implementation from this repo (it is still part of the repo's history).

**Comment by mookid8000** [comment]
I just got an idea though: I can definitely see how blob storage could be a pretty awesome super-scalable way of storing saga data, so if one could accept the constraint that sagas could only be looked up by their ID, it could definitely be made to work in a robust way.

**Comment by runes83** [comment]
That was the way I used it as only ID lookup, then it works very fine, SQL for example does not scale that well and have limitations with big saga data.
Is it possible to get an error at startup if using this type of sagastorage (only support ID lookup) if other than id is used in CorrelateMessages ?

**Comment by mookid8000** [comment]
Unfortunately it will not be possible to throw an error until runtime when handling the first message that hits the saga handler 

Sendt fra min iPhone

-
Mogens Heller Grabe
Torsmark 4
8700 Horsens
Danmark

(+45) 29 36 70 77
mookid8000@gmail.com

**Comment by runes83** [comment]
Ok then it will we a SagaDataStorageProvider at your own risk.
